### PR TITLE
Historical Data Model

### PR DESCRIPTION
**Pull request by michaelachrisco**
The branch lets us enable use of historical data to find the most interesting subreddit relations over time. 

The similarity relation task has been disabled at this time due to incompatibilities with historical data. It may need to be removed completely at a later time, but have not decided yet. TFIDFCreateRelatedSubreddits has always been a bit cleaner than using the simularity gem...

### CODE REVIEW

**Comment by michaelachrisco** [comment]
@stephengtuggy Whenever you have time, can you take a look/try out to see if the current implementation makes sense? I plan on popping out some views in another branch...sometime.

**Comment by michaelachrisco** [comment]
@stephengtuggy Postgres didn't like a double relation so I just added it as an integer. Its not going to change the operation of the app. If we need to, we can revisit, but since the tests pass, I am happy.

**Comment by stephengtuggy** [comment]
@michaelachrisco : For some reason, this branch includes pretty much the same gem updates that @deppbot introduced. They don't work for me.

First, web-console v3.1.1 depends on Ruby 2.2.x, which is a newer version of Ruby than is available on Ubuntu right now. The latest you can get on Ubuntu is ruby 2.1.5p273. I think instead, we should use web-console v2.3.0; as far as I can tell, it is a backported version of this gem with all the latest security updates included.

Second, rake v10.5.0, specified by subreddit-recommender itself as a dependency, causes problems. There seems to be a conflict between v10.5.0 and rake v10.4.2, specified in the following files:

```
./vendor/bundle/ruby/2.1.0/gems/reddit_bag_of_words-0.1.2/Gemfile.lock
./vendor/bundle/ruby/2.1.0/gems/factory_girl_rails-4.6.0/Gemfile.lock
./vendor/bundle/ruby/2.1.0/gems/awesome_print-1.6.1/Gemfile.lock
./vendor/bundle/ruby/2.1.0/gems/i18n-0.7.0/gemfiles/Gemfile.rails-3.2.x.lock
./vendor/bundle/ruby/2.1.0/gems/i18n-0.7.0/gemfiles/Gemfile.rails-master.lock
./vendor/bundle/ruby/2.1.0/gems/i18n-0.7.0/gemfiles/Gemfile.rails-4.0.x.lock
./vendor/bundle/ruby/2.1.0/gems/i18n-0.7.0/gemfiles/Gemfile.rails-4.2.x.lock
./vendor/bundle/ruby/2.1.0/gems/i18n-0.7.0/gemfiles/Gemfile.rails-4.1.x.lock
./vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/doc/rake.1
./vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/History.rdoc
./vendor/bundle/ruby/2.1.0/gems/rspec-core-3.4.2/lib/rspec/core/bisect/runner.rb
```

(I got this list by running the following:)

```
find . -exec agrep -l '10\.4\.2' {} ';'
```

**Comment by stephengtuggy** [comment]
I'm not 100% sure exactly what the problem is with rake v10.5.0. But I did notice that these Gemfile.lock files included a different version of rake.

**Comment by stephengtuggy** [comment]
Again, the latest version of rake doesn't seem to be available on Ubuntu 15.10, at least not as a .deb package. I tried getting around this by running, e.g.:

```
bundle exec rake bower:install
```

But that didn't work either. I got this error message:

```
LoadError: cannot load such file -- binding_of_caller
```

**Comment by michaelachrisco** [comment]
ill take a look. if the bag-of-words gem needs to be updated, ill make sure its not hard coding in the gems.

**Comment by michaelachrisco** [comment]
@stephengtuggy If you want to, you can merge this PR. I believe we have sorted out the issues. 

As a side note, Ubuntu can use rvm to install 2.2.2 like I did on my test machine. This whole branch was created using an Ubuntu machine but with rvm instead of Ubuntu default packages.

**Comment by stephengtuggy** [comment]
Merged.

I will try out rvm. Sounds like a good idea.

**Comment by michaelachrisco** [comment]
Thanks!

**Pull request merged**
