### PR TITLE
More on ubuntu scripts (and Vagrantfile) -- merge to michaelachrisco master

### PR DESCRIPTION
**Pull request by stephengtuggy**

### CODE REVIEW

**Comment by stephengtuggy** [comment]
@michaelachrisco , I did some more work on the ubuntu scripts, and added a Vagrantfile. It doesn't work perfectly. The /vagrant/ shared folder between host machine and guest machine seems to be messing up the line endings, so a lot of things don't work unless I download subreddit-recommender separately, into another directory on the guest. But once I do that, I can get it to build and run.

Even then, though, I can't access localhost:3000 except from the command line, inside the guest machine or using vagrant ssh on the host. The Ubuntu 15.10 boxes available on vagrantup.com are all the server version. Graphical desktop environment not included, unless I download like 2 GB worth of extra packages.

So the Vagrant setup still needs some work. But at least I can provision the box automatically to include all the prerequisite .deb and npm packages, and then get subreddit-recommender to build and run. I think I will leave it there for the moment.

**Comment by michaelachrisco** [comment]
Taking a look. Thanks for the feature!

**Comment by stephengtuggy** [comment]
You're welcome.

**Comment by stephengtuggy** [comment]
OK, I added some more commands to the provisioning shell script in the Vagrantfile. It now downloads subreddit-recommender to a VM-local directory automatically, and runs bundler and rake db:reset. I'm a lot happier with it now.

**Comment by michaelachrisco** [comment]
:beers: Ill take a look on my local machine today. Apologies, I've been busy at work and haven't had time to really dive into this one.

**Comment by stephengtuggy** [comment]
No problem.

**Comment by michaelachrisco** [comment]
I was able to get vagrant working. I like the default postgres instance. I would say, put a small blurb in the README file about the feature and ill merge. Awesome job!

**Comment by stephengtuggy** [comment]
Thanks! README blurb is done.

**Pull request merged**
