### PR TITLE
More on Vagrantfile and Ubuntu scripts, including new rvm option

### PR DESCRIPTION
**Pull request by stephengtuggy**
Note that the Vagrantfile itself doesn't actually use rvm. Instead, it uses the Ubuntu package ruby2.2. I found that this worked equally well.

### CODE REVIEW

**Comment by stephengtuggy** [comment]
@michaelachrisco , do you mind if I go ahead and merge this myself?

**Comment by michaelachrisco** [comment]
If you don't mind, I would like to take a look on my own box for reference.

**Comment by stephengtuggy** [comment]
No problem.

**Comment by michaelachrisco** [comment]
Took a look. Good :) Apologies for the wait.

**Comment by stephengtuggy** [comment]
No worries.

**Pull request merged**
